title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
avatar: https://avatars3.githubusercontent.com/u/52154100?s=400&u=fd1e6818eb26444f084fb005bf2c4af00d6a04dc&v=4

url: "http://example.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"

gems:
  - octopress-paginate

theme: jekyll-theme-cayman
